version: '3'

vars:
  IMAGE_NAME: leanix-mcp-server
  IMAGE_TAG: latest
  REGISTRY: "gtonic"

tasks:
  build:
    desc: Build the Docker image for the LeanIX MCP server
    cmds:
      - docker build -t {{.IMAGE_NAME}}:{{.IMAGE_TAG}} .

  publish:
    desc: Publish the Docker image to a registry (set REGISTRY var)
    cmds:
      - |
        if [ -z "{{.REGISTRY}}" ]; then
          echo "Set REGISTRY variable to your Docker registry (e.g. REGISTRY=ghcr.io/youruser)"; exit 1;
        fi
        docker tag {{.IMAGE_NAME}}:{{.IMAGE_TAG}} {{.REGISTRY}}/{{.IMAGE_NAME}}:{{.IMAGE_TAG}}
        docker push {{.REGISTRY}}/{{.IMAGE_NAME}}:{{.IMAGE_TAG}}

  run:
    desc: Run the LeanIX MCP server Docker container with .env
    cmds:
      - docker run --rm --env-file .env {{.IMAGE_NAME}}:{{.IMAGE_TAG}}
